'use strict';

export const figLinks = ["assets/images/itch-to-stitch-logo-static.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA23021_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA23002_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA21212_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22983_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22990_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22963_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22918_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22900_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22941_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22936_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22937_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22933_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22906_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22895_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA21211_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22914_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22695_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22770_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA18144_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22820_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22869_hires.jpg",
    "https://www.jpl.nasa.gov/spaceimages/images/largesize/PIA22569_hires.jpg"];